// Code generated by protoc-gen-go. DO NOT EDIT.
// source: agent.proto

/*
Package api is a generated protocol buffer package.

It is generated from these files:
	agent.proto
	schema.proto
	worker.proto

It has these top-level messages:
	DoJobRequest
	Label
	Meta
	Entity
	Job
	Seed
	Parameter
	QueuedSeed
	RateLimit
	WorkRequest
	WorkReply
*/
package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/empty"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type DoJobRequest struct {
	Job  *Job  `protobuf:"bytes,1,opt,name=job" json:"job,omitempty"`
	Seed *Seed `protobuf:"bytes,2,opt,name=seed" json:"seed,omitempty"`
}

func (m *DoJobRequest) Reset()                    { *m = DoJobRequest{} }
func (m *DoJobRequest) String() string            { return proto.CompactTextString(m) }
func (*DoJobRequest) ProtoMessage()               {}
func (*DoJobRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *DoJobRequest) GetJob() *Job {
	if m != nil {
		return m.Job
	}
	return nil
}

func (m *DoJobRequest) GetSeed() *Seed {
	if m != nil {
		return m.Seed
	}
	return nil
}

func init() {
	proto.RegisterType((*DoJobRequest)(nil), "api.DoJobRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Agent service

type AgentClient interface {
	Do(ctx context.Context, in *DoJobRequest, opts ...grpc.CallOption) (*google_protobuf.Empty, error)
}

type agentClient struct {
	cc *grpc.ClientConn
}

func NewAgentClient(cc *grpc.ClientConn) AgentClient {
	return &agentClient{cc}
}

func (c *agentClient) Do(ctx context.Context, in *DoJobRequest, opts ...grpc.CallOption) (*google_protobuf.Empty, error) {
	out := new(google_protobuf.Empty)
	err := grpc.Invoke(ctx, "/api.Agent/Do", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Agent service

type AgentServer interface {
	Do(context.Context, *DoJobRequest) (*google_protobuf.Empty, error)
}

func RegisterAgentServer(s *grpc.Server, srv AgentServer) {
	s.RegisterService(&_Agent_serviceDesc, srv)
}

func _Agent_Do_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DoJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).Do(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Agent/Do",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).Do(ctx, req.(*DoJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Agent_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Agent",
	HandlerType: (*AgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Do",
			Handler:    _Agent_Do_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "agent.proto",
}

func init() { proto.RegisterFile("agent.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 174 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4e, 0x4c, 0x4f, 0xcd,
	0x2b, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4e, 0x2c, 0xc8, 0x94, 0x92, 0x4e, 0xcf,
	0xcf, 0x4f, 0xcf, 0x49, 0xd5, 0x07, 0x0b, 0x25, 0x95, 0xa6, 0xe9, 0xa7, 0xe6, 0x16, 0x94, 0x54,
	0x42, 0x54, 0x48, 0xf1, 0x14, 0x27, 0x67, 0xa4, 0xe6, 0x26, 0x42, 0x78, 0x4a, 0x9e, 0x5c, 0x3c,
	0x2e, 0xf9, 0x5e, 0xf9, 0x49, 0x41, 0xa9, 0x85, 0xa5, 0xa9, 0xc5, 0x25, 0x42, 0x52, 0x5c, 0xcc,
	0x59, 0xf9, 0x49, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0xdc, 0x46, 0x1c, 0x7a, 0x89, 0x05, 0x99, 0x7a,
	0x20, 0x59, 0x90, 0xa0, 0x90, 0x2c, 0x17, 0x4b, 0x71, 0x6a, 0x6a, 0x8a, 0x04, 0x13, 0x58, 0x92,
	0x13, 0x2c, 0x19, 0x9c, 0x9a, 0x9a, 0x12, 0x04, 0x16, 0x36, 0xb2, 0xe2, 0x62, 0x75, 0x04, 0xb9,
	0x44, 0xc8, 0x90, 0x8b, 0xc9, 0x25, 0x5f, 0x48, 0x10, 0x2c, 0x8f, 0x6c, 0xb8, 0x94, 0x98, 0x1e,
	0xc4, 0x61, 0x7a, 0x30, 0x87, 0xe9, 0xb9, 0x82, 0x1c, 0xa6, 0xc4, 0x90, 0xc4, 0x06, 0x16, 0x31,
	0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0xdc, 0x68, 0x12, 0xc1, 0xcc, 0x00, 0x00, 0x00,
}
