// Code generated by protoc-gen-go. DO NOT EDIT.
// source: schema.proto

package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf1 "github.com/golang/protobuf/ptypes/timestamp"
import _ "github.com/golang/protobuf/ptypes/any"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Label struct {
	Key   string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
}

func (m *Label) Reset()                    { *m = Label{} }
func (m *Label) String() string            { return proto.CompactTextString(m) }
func (*Label) ProtoMessage()               {}
func (*Label) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *Label) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Label) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type Meta struct {
	Name           string                      `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Description    string                      `protobuf:"bytes,2,opt,name=description" json:"description,omitempty"`
	Created        *google_protobuf1.Timestamp `protobuf:"bytes,3,opt,name=created" json:"created,omitempty"`
	CreatedBy      string                      `protobuf:"bytes,4,opt,name=created_by,json=createdBy" json:"created_by,omitempty"`
	LastModified   *google_protobuf1.Timestamp `protobuf:"bytes,5,opt,name=last_modified,json=lastModified" json:"last_modified,omitempty"`
	LastModifiedBy string                      `protobuf:"bytes,6,opt,name=last_modified_by,json=lastModifiedBy" json:"last_modified_by,omitempty"`
	Label          []*Label                    `protobuf:"bytes,7,rep,name=label" json:"label,omitempty"`
}

func (m *Meta) Reset()                    { *m = Meta{} }
func (m *Meta) String() string            { return proto.CompactTextString(m) }
func (*Meta) ProtoMessage()               {}
func (*Meta) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *Meta) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Meta) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Meta) GetCreated() *google_protobuf1.Timestamp {
	if m != nil {
		return m.Created
	}
	return nil
}

func (m *Meta) GetCreatedBy() string {
	if m != nil {
		return m.CreatedBy
	}
	return ""
}

func (m *Meta) GetLastModified() *google_protobuf1.Timestamp {
	if m != nil {
		return m.LastModified
	}
	return nil
}

func (m *Meta) GetLastModifiedBy() string {
	if m != nil {
		return m.LastModifiedBy
	}
	return ""
}

func (m *Meta) GetLabel() []*Label {
	if m != nil {
		return m.Label
	}
	return nil
}

type Entity struct {
	Id   string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Meta *Meta  `protobuf:"bytes,2,opt,name=meta" json:"meta,omitempty"`
}

func (m *Entity) Reset()                    { *m = Entity{} }
func (m *Entity) String() string            { return proto.CompactTextString(m) }
func (*Entity) ProtoMessage()               {}
func (*Entity) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *Entity) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Entity) GetMeta() *Meta {
	if m != nil {
		return m.Meta
	}
	return nil
}

type Job struct {
	Id             string                      `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Meta           *Meta                       `protobuf:"bytes,2,opt,name=meta" json:"meta,omitempty"`
	CronExpression string                      `protobuf:"bytes,3,opt,name=cron_expression,json=cronExpression" json:"cron_expression,omitempty"`
	ValidFrom      *google_protobuf1.Timestamp `protobuf:"bytes,4,opt,name=valid_from,json=validFrom" json:"valid_from,omitempty"`
	ValidTo        *google_protobuf1.Timestamp `protobuf:"bytes,5,opt,name=valid_to,json=validTo" json:"valid_to,omitempty"`
	Disabled       bool                        `protobuf:"varint,15,opt,name=disabled" json:"disabled,omitempty"`
}

func (m *Job) Reset()                    { *m = Job{} }
func (m *Job) String() string            { return proto.CompactTextString(m) }
func (*Job) ProtoMessage()               {}
func (*Job) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

func (m *Job) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Job) GetMeta() *Meta {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *Job) GetCronExpression() string {
	if m != nil {
		return m.CronExpression
	}
	return ""
}

func (m *Job) GetValidFrom() *google_protobuf1.Timestamp {
	if m != nil {
		return m.ValidFrom
	}
	return nil
}

func (m *Job) GetValidTo() *google_protobuf1.Timestamp {
	if m != nil {
		return m.ValidTo
	}
	return nil
}

func (m *Job) GetDisabled() bool {
	if m != nil {
		return m.Disabled
	}
	return false
}

type Seed struct {
	Id       string   `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Meta     *Meta    `protobuf:"bytes,2,opt,name=meta" json:"meta,omitempty"`
	EntityId string   `protobuf:"bytes,3,opt,name=entity_id,json=entityId" json:"entity_id,omitempty"`
	JobId    []string `protobuf:"bytes,4,rep,name=job_id,json=jobId" json:"job_id,omitempty"`
	Disabled bool     `protobuf:"varint,15,opt,name=disabled" json:"disabled,omitempty"`
}

func (m *Seed) Reset()                    { *m = Seed{} }
func (m *Seed) String() string            { return proto.CompactTextString(m) }
func (*Seed) ProtoMessage()               {}
func (*Seed) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{4} }

func (m *Seed) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Seed) GetMeta() *Meta {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *Seed) GetEntityId() string {
	if m != nil {
		return m.EntityId
	}
	return ""
}

func (m *Seed) GetJobId() []string {
	if m != nil {
		return m.JobId
	}
	return nil
}

func (m *Seed) GetDisabled() bool {
	if m != nil {
		return m.Disabled
	}
	return false
}

type Parameter struct {
	Id      string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Query   string `protobuf:"bytes,3,opt,name=query" json:"query,omitempty"`
	MaxId   string `protobuf:"bytes,4,opt,name=max_id,json=maxId" json:"max_id,omitempty"`
	SinceId string `protobuf:"bytes,5,opt,name=since_id,json=sinceId" json:"since_id,omitempty"`
}

func (m *Parameter) Reset()                    { *m = Parameter{} }
func (m *Parameter) String() string            { return proto.CompactTextString(m) }
func (*Parameter) ProtoMessage()               {}
func (*Parameter) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{5} }

func (m *Parameter) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Parameter) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

func (m *Parameter) GetMaxId() string {
	if m != nil {
		return m.MaxId
	}
	return ""
}

func (m *Parameter) GetSinceId() string {
	if m != nil {
		return m.SinceId
	}
	return ""
}

type QueuedSeed struct {
	Id        string     `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Seq       int32      `protobuf:"varint,2,opt,name=seq" json:"seq,omitempty"`
	Ref       string     `protobuf:"bytes,3,opt,name=ref" json:"ref,omitempty"`
	SeedId    string     `protobuf:"bytes,4,opt,name=seed_id,json=seedId" json:"seed_id,omitempty"`
	Parameter *Parameter `protobuf:"bytes,5,opt,name=parameter" json:"parameter,omitempty"`
}

func (m *QueuedSeed) Reset()                    { *m = QueuedSeed{} }
func (m *QueuedSeed) String() string            { return proto.CompactTextString(m) }
func (*QueuedSeed) ProtoMessage()               {}
func (*QueuedSeed) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{6} }

func (m *QueuedSeed) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *QueuedSeed) GetSeq() int32 {
	if m != nil {
		return m.Seq
	}
	return 0
}

func (m *QueuedSeed) GetRef() string {
	if m != nil {
		return m.Ref
	}
	return ""
}

func (m *QueuedSeed) GetSeedId() string {
	if m != nil {
		return m.SeedId
	}
	return ""
}

func (m *QueuedSeed) GetParameter() *Parameter {
	if m != nil {
		return m.Parameter
	}
	return nil
}

type RateLimit struct {
	Limit     int32                       `protobuf:"varint,1,opt,name=limit" json:"limit,omitempty"`
	Remaining int32                       `protobuf:"varint,2,opt,name=remaining" json:"remaining,omitempty"`
	Reset_    *google_protobuf1.Timestamp `protobuf:"bytes,3,opt,name=reset" json:"reset,omitempty"`
}

func (m *RateLimit) Reset()                    { *m = RateLimit{} }
func (m *RateLimit) String() string            { return proto.CompactTextString(m) }
func (*RateLimit) ProtoMessage()               {}
func (*RateLimit) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{7} }

func (m *RateLimit) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *RateLimit) GetRemaining() int32 {
	if m != nil {
		return m.Remaining
	}
	return 0
}

func (m *RateLimit) GetReset_() *google_protobuf1.Timestamp {
	if m != nil {
		return m.Reset_
	}
	return nil
}

func init() {
	proto.RegisterType((*Label)(nil), "api.Label")
	proto.RegisterType((*Meta)(nil), "api.Meta")
	proto.RegisterType((*Entity)(nil), "api.Entity")
	proto.RegisterType((*Job)(nil), "api.Job")
	proto.RegisterType((*Seed)(nil), "api.Seed")
	proto.RegisterType((*Parameter)(nil), "api.Parameter")
	proto.RegisterType((*QueuedSeed)(nil), "api.QueuedSeed")
	proto.RegisterType((*RateLimit)(nil), "api.RateLimit")
}

func init() { proto.RegisterFile("schema.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 578 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0xdd, 0x6e, 0xd3, 0x4c,
	0x10, 0x95, 0x63, 0x3b, 0x89, 0x27, 0xfd, 0xda, 0x6a, 0xd5, 0x4f, 0xb8, 0x01, 0x84, 0xe5, 0x1b,
	0x72, 0x81, 0x5c, 0x54, 0x40, 0x88, 0x2b, 0xa4, 0x4a, 0x45, 0x0a, 0x6a, 0x25, 0x30, 0xbd, 0x8f,
	0xd6, 0xde, 0x49, 0xd9, 0xe2, 0xf5, 0xba, 0xeb, 0x4d, 0x55, 0x3f, 0x00, 0xe2, 0x2d, 0x78, 0x41,
	0x5e, 0x02, 0xed, 0xae, 0xd3, 0x96, 0x1f, 0x95, 0xf6, 0x6e, 0xe6, 0xcc, 0x99, 0x9d, 0x73, 0x4e,
	0x62, 0xd8, 0x68, 0xcb, 0xcf, 0x28, 0x68, 0xd6, 0x28, 0xa9, 0x25, 0xf1, 0x69, 0xc3, 0xa7, 0x4f,
	0x4e, 0xa5, 0x3c, 0xad, 0x70, 0xcf, 0x42, 0xc5, 0x6a, 0xb9, 0xa7, 0xb9, 0xc0, 0x56, 0x53, 0xd1,
	0x38, 0xd6, 0x74, 0xf7, 0x77, 0x02, 0xad, 0x3b, 0x37, 0x4a, 0xf7, 0x20, 0x3c, 0xa2, 0x05, 0x56,
	0x64, 0x1b, 0xfc, 0x2f, 0xd8, 0xc5, 0x5e, 0xe2, 0xcd, 0xa2, 0xdc, 0x94, 0x64, 0x07, 0xc2, 0x0b,
	0x5a, 0xad, 0x30, 0x1e, 0x58, 0xcc, 0x35, 0xe9, 0xf7, 0x01, 0x04, 0xc7, 0xa8, 0x29, 0x21, 0x10,
	0xd4, 0x54, 0x60, 0xbf, 0x61, 0x6b, 0x92, 0xc0, 0x84, 0x61, 0x5b, 0x2a, 0xde, 0x68, 0x2e, 0xeb,
	0x7e, 0xf1, 0x26, 0x44, 0x5e, 0xc2, 0xa8, 0x54, 0x48, 0x35, 0xb2, 0xd8, 0x4f, 0xbc, 0xd9, 0x64,
	0x7f, 0x9a, 0x39, 0x71, 0xd9, 0x5a, 0x5c, 0x76, 0xb2, 0x56, 0x9f, 0xaf, 0xa9, 0xe4, 0x31, 0x40,
	0x5f, 0x2e, 0x8a, 0x2e, 0x0e, 0xec, 0xb3, 0x51, 0x8f, 0x1c, 0x74, 0xe4, 0x2d, 0xfc, 0x57, 0xd1,
	0x56, 0x2f, 0x84, 0x64, 0x7c, 0xc9, 0x91, 0xc5, 0xe1, 0x3f, 0x9f, 0xde, 0x30, 0x0b, 0xc7, 0x3d,
	0x9f, 0xcc, 0x60, 0xfb, 0x97, 0x07, 0xcc, 0x95, 0xa1, 0xbd, 0xb2, 0x79, 0x93, 0x77, 0xd0, 0x91,
	0x04, 0xc2, 0xca, 0xe4, 0x15, 0x8f, 0x12, 0x7f, 0x36, 0xd9, 0x87, 0x8c, 0x36, 0x3c, 0xb3, 0x09,
	0xe6, 0x6e, 0x90, 0xbe, 0x86, 0xe1, 0x61, 0xad, 0xb9, 0xee, 0xc8, 0x26, 0x0c, 0x38, 0xeb, 0xf3,
	0x19, 0x70, 0xe3, 0x22, 0x10, 0xa8, 0xa9, 0x8d, 0x65, 0xb2, 0x1f, 0xd9, 0x55, 0x13, 0x65, 0x6e,
	0xe1, 0xf4, 0x87, 0x07, 0xfe, 0x7b, 0x59, 0xdc, 0x73, 0x8d, 0x3c, 0x85, 0xad, 0x52, 0xc9, 0x7a,
	0x81, 0x97, 0x8d, 0xc2, 0xb6, 0x35, 0xb9, 0xfb, 0x4e, 0xba, 0x81, 0x0f, 0xaf, 0x50, 0xf2, 0x06,
	0xe0, 0x82, 0x56, 0x9c, 0x2d, 0x96, 0x4a, 0x0a, 0x1b, 0xe2, 0xed, 0x11, 0x45, 0x96, 0xfd, 0x4e,
	0x49, 0x41, 0x5e, 0xc1, 0xd8, 0xad, 0x6a, 0x79, 0x87, 0x6c, 0x47, 0x96, 0x7b, 0x22, 0xc9, 0x14,
	0xc6, 0x8c, 0xb7, 0xb4, 0xa8, 0x90, 0xc5, 0x5b, 0x89, 0x37, 0x1b, 0xe7, 0x57, 0x7d, 0xfa, 0xd5,
	0x83, 0xe0, 0x13, 0x22, 0xbb, 0xaf, 0xdd, 0x87, 0x10, 0xa1, 0x8d, 0x77, 0xc1, 0x59, 0x6f, 0x74,
	0xec, 0x80, 0x39, 0x23, 0xff, 0xc3, 0xf0, 0x4c, 0x16, 0x66, 0x12, 0x24, 0xbe, 0xf9, 0xcf, 0x9e,
	0xc9, 0x62, 0xce, 0x6e, 0xd5, 0x51, 0x42, 0xf4, 0x81, 0x2a, 0x2a, 0x50, 0xa3, 0xfa, 0x43, 0xcb,
	0x0e, 0x84, 0xe7, 0x2b, 0x54, 0x5d, 0x7f, 0xc8, 0x35, 0xe6, 0x8a, 0xa0, 0x97, 0xee, 0x8a, 0x85,
	0x05, 0xbd, 0x9c, 0x33, 0xb2, 0x0b, 0xe3, 0x96, 0xd7, 0x25, 0x9a, 0x41, 0x68, 0x07, 0x23, 0xdb,
	0xcf, 0x59, 0xfa, 0xcd, 0x03, 0xf8, 0xb8, 0xc2, 0x15, 0xb2, 0xbf, 0x5a, 0xde, 0x06, 0xbf, 0xc5,
	0x73, 0xeb, 0x38, 0xcc, 0x4d, 0x69, 0x10, 0x85, 0xcb, 0xfe, 0xac, 0x29, 0xc9, 0x03, 0x18, 0xb5,
	0x88, 0xec, 0xfa, 0xea, 0xd0, 0xb4, 0x73, 0x46, 0x9e, 0x41, 0xd4, 0xac, 0x0d, 0xf4, 0x3f, 0xce,
	0xa6, 0x0d, 0xed, 0xca, 0x56, 0x7e, 0x4d, 0x48, 0xcf, 0x21, 0xca, 0xa9, 0xc6, 0x23, 0x2e, 0xb8,
	0x36, 0xf6, 0x2a, 0x53, 0x58, 0x29, 0x61, 0xee, 0x1a, 0xf2, 0x08, 0x22, 0x85, 0x82, 0xf2, 0x9a,
	0xd7, 0xa7, 0xbd, 0xa6, 0x6b, 0x80, 0x3c, 0x87, 0x50, 0x61, 0x8b, 0xfa, 0x0e, 0x9f, 0xaf, 0x23,
	0x16, 0x43, 0x3b, 0x7a, 0xf1, 0x33, 0x00, 0x00, 0xff, 0xff, 0xd2, 0x83, 0x12, 0xa0, 0xba, 0x04,
	0x00, 0x00,
}
