// Code generated by protoc-gen-go. DO NOT EDIT.
// source: schema.proto

package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf1 "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Label struct {
	Key   string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
}

func (m *Label) Reset()                    { *m = Label{} }
func (m *Label) String() string            { return proto.CompactTextString(m) }
func (*Label) ProtoMessage()               {}
func (*Label) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *Label) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *Label) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type Meta struct {
	Name           string                      `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Description    string                      `protobuf:"bytes,2,opt,name=description" json:"description,omitempty"`
	Created        *google_protobuf1.Timestamp `protobuf:"bytes,3,opt,name=created" json:"created,omitempty"`
	CreatedBy      string                      `protobuf:"bytes,4,opt,name=created_by,json=createdBy" json:"created_by,omitempty"`
	LastModified   *google_protobuf1.Timestamp `protobuf:"bytes,5,opt,name=last_modified,json=lastModified" json:"last_modified,omitempty"`
	LastModifiedBy string                      `protobuf:"bytes,6,opt,name=last_modified_by,json=lastModifiedBy" json:"last_modified_by,omitempty"`
	Label          []*Label                    `protobuf:"bytes,7,rep,name=label" json:"label,omitempty"`
}

func (m *Meta) Reset()                    { *m = Meta{} }
func (m *Meta) String() string            { return proto.CompactTextString(m) }
func (*Meta) ProtoMessage()               {}
func (*Meta) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *Meta) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Meta) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Meta) GetCreated() *google_protobuf1.Timestamp {
	if m != nil {
		return m.Created
	}
	return nil
}

func (m *Meta) GetCreatedBy() string {
	if m != nil {
		return m.CreatedBy
	}
	return ""
}

func (m *Meta) GetLastModified() *google_protobuf1.Timestamp {
	if m != nil {
		return m.LastModified
	}
	return nil
}

func (m *Meta) GetLastModifiedBy() string {
	if m != nil {
		return m.LastModifiedBy
	}
	return ""
}

func (m *Meta) GetLabel() []*Label {
	if m != nil {
		return m.Label
	}
	return nil
}

type Entity struct {
	Id   string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Meta *Meta  `protobuf:"bytes,2,opt,name=meta" json:"meta,omitempty"`
}

func (m *Entity) Reset()                    { *m = Entity{} }
func (m *Entity) String() string            { return proto.CompactTextString(m) }
func (*Entity) ProtoMessage()               {}
func (*Entity) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *Entity) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Entity) GetMeta() *Meta {
	if m != nil {
		return m.Meta
	}
	return nil
}

type Job struct {
	Id             string                      `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Meta           *Meta                       `protobuf:"bytes,2,opt,name=meta" json:"meta,omitempty"`
	CronExpression string                      `protobuf:"bytes,3,opt,name=cron_expression,json=cronExpression" json:"cron_expression,omitempty"`
	ValidFrom      *google_protobuf1.Timestamp `protobuf:"bytes,4,opt,name=valid_from,json=validFrom" json:"valid_from,omitempty"`
	ValidTo        *google_protobuf1.Timestamp `protobuf:"bytes,5,opt,name=valid_to,json=validTo" json:"valid_to,omitempty"`
	Disabled       bool                        `protobuf:"varint,15,opt,name=disabled" json:"disabled,omitempty"`
}

func (m *Job) Reset()                    { *m = Job{} }
func (m *Job) String() string            { return proto.CompactTextString(m) }
func (*Job) ProtoMessage()               {}
func (*Job) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

func (m *Job) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Job) GetMeta() *Meta {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *Job) GetCronExpression() string {
	if m != nil {
		return m.CronExpression
	}
	return ""
}

func (m *Job) GetValidFrom() *google_protobuf1.Timestamp {
	if m != nil {
		return m.ValidFrom
	}
	return nil
}

func (m *Job) GetValidTo() *google_protobuf1.Timestamp {
	if m != nil {
		return m.ValidTo
	}
	return nil
}

func (m *Job) GetDisabled() bool {
	if m != nil {
		return m.Disabled
	}
	return false
}

type Seed struct {
	Id       string   `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Meta     *Meta    `protobuf:"bytes,2,opt,name=meta" json:"meta,omitempty"`
	EntityId string   `protobuf:"bytes,3,opt,name=entity_id,json=entityId" json:"entity_id,omitempty"`
	JobId    []string `protobuf:"bytes,4,rep,name=job_id,json=jobId" json:"job_id,omitempty"`
	Disabled bool     `protobuf:"varint,15,opt,name=disabled" json:"disabled,omitempty"`
}

func (m *Seed) Reset()                    { *m = Seed{} }
func (m *Seed) String() string            { return proto.CompactTextString(m) }
func (*Seed) ProtoMessage()               {}
func (*Seed) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{4} }

func (m *Seed) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Seed) GetMeta() *Meta {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *Seed) GetEntityId() string {
	if m != nil {
		return m.EntityId
	}
	return ""
}

func (m *Seed) GetJobId() []string {
	if m != nil {
		return m.JobId
	}
	return nil
}

func (m *Seed) GetDisabled() bool {
	if m != nil {
		return m.Disabled
	}
	return false
}

type Parameter struct {
	Id              string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Query           string `protobuf:"bytes,3,opt,name=query" json:"query,omitempty"`
	MaxId           string `protobuf:"bytes,4,opt,name=max_id,json=maxId" json:"max_id,omitempty"`
	SinceId         string `protobuf:"bytes,5,opt,name=since_id,json=sinceId" json:"since_id,omitempty"`
	Geocode         string `protobuf:"bytes,6,opt,name=geocode" json:"geocode,omitempty"`
	Lang            string `protobuf:"bytes,7,opt,name=lang" json:"lang,omitempty"`
	ResultType      string `protobuf:"bytes,8,opt,name=result_type,json=resultType" json:"result_type,omitempty"`
	Count           int32  `protobuf:"varint,9,opt,name=count" json:"count,omitempty"`
	Until           string `protobuf:"bytes,10,opt,name=until" json:"until,omitempty"`
	IncludeEntities bool   `protobuf:"varint,11,opt,name=include_entities,json=includeEntities" json:"include_entities,omitempty"`
	TweetMode       string `protobuf:"bytes,12,opt,name=tweet_mode,json=tweetMode" json:"tweet_mode,omitempty"`
	Locale          string `protobuf:"bytes,13,opt,name=locale" json:"locale,omitempty"`
}

func (m *Parameter) Reset()                    { *m = Parameter{} }
func (m *Parameter) String() string            { return proto.CompactTextString(m) }
func (*Parameter) ProtoMessage()               {}
func (*Parameter) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{5} }

func (m *Parameter) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Parameter) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

func (m *Parameter) GetMaxId() string {
	if m != nil {
		return m.MaxId
	}
	return ""
}

func (m *Parameter) GetSinceId() string {
	if m != nil {
		return m.SinceId
	}
	return ""
}

func (m *Parameter) GetGeocode() string {
	if m != nil {
		return m.Geocode
	}
	return ""
}

func (m *Parameter) GetLang() string {
	if m != nil {
		return m.Lang
	}
	return ""
}

func (m *Parameter) GetResultType() string {
	if m != nil {
		return m.ResultType
	}
	return ""
}

func (m *Parameter) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *Parameter) GetUntil() string {
	if m != nil {
		return m.Until
	}
	return ""
}

func (m *Parameter) GetIncludeEntities() bool {
	if m != nil {
		return m.IncludeEntities
	}
	return false
}

func (m *Parameter) GetTweetMode() string {
	if m != nil {
		return m.TweetMode
	}
	return ""
}

func (m *Parameter) GetLocale() string {
	if m != nil {
		return m.Locale
	}
	return ""
}

type QueuedSeed struct {
	Id        string     `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Seq       int32      `protobuf:"varint,2,opt,name=seq" json:"seq,omitempty"`
	Ref       string     `protobuf:"bytes,3,opt,name=ref" json:"ref,omitempty"`
	SeedId    string     `protobuf:"bytes,4,opt,name=seed_id,json=seedId" json:"seed_id,omitempty"`
	Parameter *Parameter `protobuf:"bytes,5,opt,name=parameter" json:"parameter,omitempty"`
}

func (m *QueuedSeed) Reset()                    { *m = QueuedSeed{} }
func (m *QueuedSeed) String() string            { return proto.CompactTextString(m) }
func (*QueuedSeed) ProtoMessage()               {}
func (*QueuedSeed) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{6} }

func (m *QueuedSeed) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *QueuedSeed) GetSeq() int32 {
	if m != nil {
		return m.Seq
	}
	return 0
}

func (m *QueuedSeed) GetRef() string {
	if m != nil {
		return m.Ref
	}
	return ""
}

func (m *QueuedSeed) GetSeedId() string {
	if m != nil {
		return m.SeedId
	}
	return ""
}

func (m *QueuedSeed) GetParameter() *Parameter {
	if m != nil {
		return m.Parameter
	}
	return nil
}

type RateLimit struct {
	Limit     int32                       `protobuf:"varint,1,opt,name=limit" json:"limit,omitempty"`
	Remaining int32                       `protobuf:"varint,2,opt,name=remaining" json:"remaining,omitempty"`
	Reset_    *google_protobuf1.Timestamp `protobuf:"bytes,3,opt,name=reset" json:"reset,omitempty"`
}

func (m *RateLimit) Reset()                    { *m = RateLimit{} }
func (m *RateLimit) String() string            { return proto.CompactTextString(m) }
func (*RateLimit) ProtoMessage()               {}
func (*RateLimit) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{7} }

func (m *RateLimit) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *RateLimit) GetRemaining() int32 {
	if m != nil {
		return m.Remaining
	}
	return 0
}

func (m *RateLimit) GetReset_() *google_protobuf1.Timestamp {
	if m != nil {
		return m.Reset_
	}
	return nil
}

func init() {
	proto.RegisterType((*Label)(nil), "api.Label")
	proto.RegisterType((*Meta)(nil), "api.Meta")
	proto.RegisterType((*Entity)(nil), "api.Entity")
	proto.RegisterType((*Job)(nil), "api.Job")
	proto.RegisterType((*Seed)(nil), "api.Seed")
	proto.RegisterType((*Parameter)(nil), "api.Parameter")
	proto.RegisterType((*QueuedSeed)(nil), "api.QueuedSeed")
	proto.RegisterType((*RateLimit)(nil), "api.RateLimit")
}

func init() { proto.RegisterFile("schema.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 687 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0xdd, 0x6e, 0xd3, 0x4a,
	0x10, 0x96, 0xe3, 0x38, 0x89, 0x27, 0xfd, 0x89, 0x56, 0x3d, 0xe7, 0xec, 0xe9, 0x39, 0xa8, 0x56,
	0x6e, 0x08, 0x12, 0x4a, 0x51, 0x01, 0x21, 0xae, 0x90, 0x2a, 0x15, 0x29, 0xa8, 0x95, 0xc0, 0xf4,
	0xde, 0x5a, 0x7b, 0x27, 0x61, 0x8b, 0xed, 0x75, 0xed, 0x75, 0xa9, 0x1f, 0x00, 0xf1, 0x16, 0x3c,
	0x0b, 0xef, 0xc3, 0x4b, 0xa0, 0xfd, 0x49, 0x5b, 0x04, 0x2a, 0xed, 0xdd, 0x7c, 0xdf, 0xcc, 0x78,
	0xbe, 0xfd, 0x76, 0xc7, 0xb0, 0xd1, 0x64, 0x1f, 0xb0, 0x60, 0xf3, 0xaa, 0x96, 0x4a, 0x12, 0x9f,
	0x55, 0x62, 0x77, 0x6f, 0x25, 0xe5, 0x2a, 0xc7, 0x7d, 0x43, 0xa5, 0xed, 0x72, 0x5f, 0x89, 0x02,
	0x1b, 0xc5, 0x8a, 0xca, 0x56, 0x4d, 0xf7, 0x21, 0x38, 0x66, 0x29, 0xe6, 0x64, 0x02, 0xfe, 0x47,
	0xec, 0xa8, 0x17, 0x79, 0xb3, 0x30, 0xd6, 0x21, 0xd9, 0x81, 0xe0, 0x82, 0xe5, 0x2d, 0xd2, 0x9e,
	0xe1, 0x2c, 0x98, 0x7e, 0xed, 0x41, 0xff, 0x04, 0x15, 0x23, 0x04, 0xfa, 0x25, 0x2b, 0xd0, 0x75,
	0x98, 0x98, 0x44, 0x30, 0xe6, 0xd8, 0x64, 0xb5, 0xa8, 0x94, 0x90, 0xa5, 0x6b, 0xbc, 0x49, 0x91,
	0x67, 0x30, 0xcc, 0x6a, 0x64, 0x0a, 0x39, 0xf5, 0x23, 0x6f, 0x36, 0x3e, 0xd8, 0x9d, 0x5b, 0x89,
	0xf3, 0xb5, 0xc4, 0xf9, 0xe9, 0x5a, 0x62, 0xbc, 0x2e, 0x25, 0x0f, 0x00, 0x5c, 0x98, 0xa4, 0x1d,
	0xed, 0x9b, 0xcf, 0x86, 0x8e, 0x39, 0xec, 0xc8, 0x2b, 0xd8, 0xcc, 0x59, 0xa3, 0x92, 0x42, 0x72,
	0xb1, 0x14, 0xc8, 0x69, 0xf0, 0xc7, 0x4f, 0x6f, 0xe8, 0x86, 0x13, 0x57, 0x4f, 0x66, 0x30, 0xf9,
	0xe9, 0x03, 0x7a, 0xca, 0xc0, 0x4c, 0xd9, 0xba, 0x59, 0x77, 0xd8, 0x91, 0x08, 0x82, 0x5c, 0xfb,
	0x45, 0x87, 0x91, 0x3f, 0x1b, 0x1f, 0xc0, 0x9c, 0x55, 0x62, 0x6e, 0x1c, 0x8c, 0x6d, 0x62, 0xfa,
	0x02, 0x06, 0x47, 0xa5, 0x12, 0xaa, 0x23, 0x5b, 0xd0, 0x13, 0xdc, 0xf9, 0xd3, 0x13, 0xfa, 0x14,
	0xfd, 0x02, 0x15, 0x33, 0xb6, 0x8c, 0x0f, 0x42, 0xd3, 0xaa, 0xad, 0x8c, 0x0d, 0x3d, 0xfd, 0xee,
	0x81, 0xff, 0x46, 0xa6, 0xf7, 0x6c, 0x23, 0x0f, 0x61, 0x3b, 0xab, 0x65, 0x99, 0xe0, 0x65, 0x55,
	0x63, 0xd3, 0x68, 0xdf, 0x7d, 0x2b, 0x5d, 0xd3, 0x47, 0x57, 0x2c, 0x79, 0x09, 0x70, 0xc1, 0x72,
	0xc1, 0x93, 0x65, 0x2d, 0x0b, 0x63, 0xe2, 0xed, 0x16, 0x85, 0xa6, 0xfa, 0x75, 0x2d, 0x0b, 0xf2,
	0x1c, 0x46, 0xb6, 0x55, 0xc9, 0x3b, 0x78, 0x3b, 0x34, 0xb5, 0xa7, 0x92, 0xec, 0xc2, 0x88, 0x8b,
	0x86, 0xa5, 0x39, 0x72, 0xba, 0x1d, 0x79, 0xb3, 0x51, 0x7c, 0x85, 0xa7, 0x9f, 0x3d, 0xe8, 0xbf,
	0x47, 0xe4, 0xf7, 0x3d, 0xee, 0x7f, 0x10, 0xa2, 0xb1, 0x37, 0x11, 0xdc, 0x1d, 0x74, 0x64, 0x89,
	0x05, 0x27, 0x7f, 0xc1, 0xe0, 0x4c, 0xa6, 0x3a, 0xd3, 0x8f, 0x7c, 0xfd, 0x66, 0xcf, 0x64, 0xba,
	0xe0, 0xb7, 0xea, 0xf8, 0xd6, 0x83, 0xf0, 0x2d, 0xab, 0x59, 0x81, 0x0a, 0xeb, 0x5f, 0xc4, 0xec,
	0x40, 0x70, 0xde, 0x62, 0xdd, 0xb9, 0x49, 0x16, 0xe8, 0x31, 0x05, 0xbb, 0xb4, 0x63, 0x0c, 0x5d,
	0xb0, 0xcb, 0x05, 0x27, 0xff, 0xc2, 0xa8, 0x11, 0x65, 0x86, 0x3a, 0x11, 0x98, 0xc4, 0xd0, 0xe0,
	0x05, 0x27, 0x14, 0x86, 0x2b, 0x94, 0x99, 0xe4, 0xe8, 0xde, 0xd5, 0x1a, 0xea, 0x35, 0xca, 0x59,
	0xb9, 0xa2, 0x43, 0xbb, 0x46, 0x3a, 0x26, 0x7b, 0x30, 0xae, 0xb1, 0x69, 0x73, 0x95, 0xa8, 0xae,
	0x42, 0x3a, 0x32, 0x29, 0xb0, 0xd4, 0x69, 0x57, 0xa1, 0x96, 0x95, 0xc9, 0xb6, 0x54, 0x34, 0x8c,
	0xbc, 0x59, 0x10, 0x5b, 0xa0, 0xd9, 0xb6, 0x54, 0x22, 0xa7, 0x60, 0x55, 0x19, 0x40, 0x1e, 0xc1,
	0x44, 0x94, 0x59, 0xde, 0x72, 0x4c, 0x8c, 0x4f, 0x02, 0x1b, 0x3a, 0x36, 0x26, 0x6c, 0x3b, 0xfe,
	0xc8, 0xd1, 0x7a, 0xcd, 0xd4, 0x27, 0x44, 0xb3, 0x07, 0x48, 0x37, 0xec, 0x9a, 0x19, 0xe6, 0x44,
	0x4b, 0xfd, 0x1b, 0x06, 0xb9, 0xcc, 0x58, 0x8e, 0x74, 0xd3, 0xa4, 0x1c, 0x9a, 0x7e, 0xf1, 0x00,
	0xde, 0xb5, 0xd8, 0x22, 0xff, 0xed, 0x85, 0x4e, 0xc0, 0x6f, 0xf0, 0xdc, 0xdc, 0x67, 0x10, 0xeb,
	0x50, 0x33, 0x35, 0x2e, 0x9d, 0xa7, 0x3a, 0x24, 0xff, 0xc0, 0xb0, 0x41, 0xe4, 0xd7, 0x96, 0x0e,
	0x34, 0x5c, 0x70, 0xf2, 0x18, 0xc2, 0x6a, 0x7d, 0x3b, 0xee, 0xe9, 0x6d, 0x99, 0x27, 0x71, 0x75,
	0x67, 0xf1, 0x75, 0xc1, 0xf4, 0x1c, 0xc2, 0x98, 0x29, 0x3c, 0x16, 0x85, 0x30, 0x76, 0xe4, 0x3a,
	0x30, 0x52, 0x82, 0xd8, 0x02, 0xf2, 0x3f, 0x84, 0x35, 0x16, 0x4c, 0x94, 0xa2, 0x5c, 0x39, 0x4d,
	0xd7, 0x04, 0x79, 0x02, 0x41, 0x8d, 0x0d, 0xaa, 0x3b, 0xfc, 0x9c, 0x6c, 0x61, 0x3a, 0x30, 0xa9,
	0xa7, 0x3f, 0x02, 0x00, 0x00, 0xff, 0xff, 0xe6, 0xce, 0xc9, 0x53, 0x7d, 0x05, 0x00, 0x00,
}
